<template>
    <div class="loadingio-spinner-rolling-p7yyk8ewj0a"><div class="ldio-0md14in4cko">
    <div></div>
    </div></div>
</template>

<style>
    @keyframes ldio-0md14in4cko {
      0% { transform: translate(-50%,-50%) rotate(0deg); }
      100% { transform: translate(-50%,-50%) rotate(360deg); }
    }
    .ldio-0md14in4cko div {
      position: absolute;
      width: 132px;
      height: 132px;
      border: 8px solid #dcdcdc;
      border-top-color: transparent;
      border-radius: 50%;
    }
    .ldio-0md14in4cko div {
      animation: ldio-0md14in4cko 1s linear infinite;
      top: 100px;
      left: 100px
    }
    .loadingio-spinner-rolling-p7yyk8ewj0a {
      width: 200px;
      height: 200px;
      display: inline-block;
      overflow: hidden;
      background: #ffffff;
    }
    .ldio-0md14in4cko {
      width: 100%;
      height: 100%;
      position: relative;
      transform: translateZ(0) scale(1);
      backface-visibility: hidden;
      transform-origin: 0 0; /* see note above */
    }
    .ldio-0md14in4cko div { box-sizing: content-box; }
    /* generated by https://loading.io/ */
</style>


   
    
   